const expenseData = [
  {
    id: 3001,
    type: "Expense",
    imageLink: "./assets/utilities.png",
    category: "Utilities",
    percentage: "",
    amount: 0,
  },
  {
    id: 3002,
    type: "Expense",
    imageLink: "./assets/food.png",
    category: "Food",
    percentage: "",
    amount: 0,
  },
  {
    id: 3003,
    type: "Expense",
    imageLink: "./assets/groceries.png",
    category: "Groceries",
    percentage: "",
    amount: 0,
  },
  {
    id: 3004,
    type: "Expense",
    imageLink: "./assets/health.png",
    category: "Health",
    percentage: "",
    amount: 0,
  },
  {
    id: 3005,
    type: "Expense",
    imageLink: "./assets/education.png",
    category: "Education",
    percentage: "",
    amount: 0,
  },
  {
    id: 3006,
    type: "Expense",
    imageLink: "./assets/transportation.png",
    category: "Transportation",
    percentage: "",
    amount: 0,
  },
  {
    id: 3007,
    type: "Expense",
    imageLink: "./assets/leisure.png",
    category: "Leisure",
    percentage: "",
    amount: 0,
  },
  {
    id: 3008,
    type: "Expense",
    imageLink: "./assets/clothes.png",
    category: "Clothes",
    percentage: "",
    amount: 0,
  },
  {
    id: 3009,
    type: "Expense",
    imageLink: "./assets/gifts.png",
    category: "Gifts",
    percentage: "",
    amount: 0,
  },
  {
    id: 3010,
    type: "Expense",
    imageLink: "./assets/others.png",
    category: "Other Expenses",
    percentage: "",
    amount: 0,
  },
];

export default expenseData;
