const MasterData = [
  {
    id: 4001,
    type: "Income",
    imageLink: "./src/assets/salary.png",
    category: "Salary",
    percentage: "%",
    amount: 0,
  },
  {
    id: 4002,
    type: "Income",
    imageLink: "./src/assets/allowance.png",
    category: "Allowance",
    percentage: "%",
    amount: 0,
  },
  {
    id: 4003,
    type: "Income",
    imageLink: "./src/assets/gifts.png",
    category: "Gifts",
    percentage: "%",
    amount: 0,
  },
  {
    id: 4004,
    type: "Income",
    imageLink: "./src/assets/others.png",
    category: "Other Income",
    percentage: "%",
    amount: 0,
  },
  {
    id: 3001,
    type: "Expense",
    imageLink: "./src/assets/utilities.png",
    category: "Utilities",
    percentage: "",
    amount: 0,
  },
  {
    id: 3002,
    type: "Expense",
    imageLink: "./src/assets/food.png",
    category: "Food",
    percentage: "",
    amount: 0,
  },
  {
    id: 3003,
    type: "Expense",
    imageLink: "./src/assets/groceries.png",
    category: "Groceries",
    percentage: "",
    amount: 0,
  },
  {
    id: 3004,
    type: "Expense",
    imageLink: "./src/assets/health.png",
    category: "Health",
    percentage: "",
    amount: 0,
  },
  {
    id: 3005,
    type: "Expense",
    imageLink: "./src/assets/education.png",
    category: "Education",
    percentage: "",
    amount: 0,
  },
  {
    id: 3006,
    type: "Expense",
    imageLink: "./src/assets/transportation.png",
    category: "Transportation",
    percentage: "",
    amount: 0,
  },
  {
    id: 3007,
    type: "Expense",
    imageLink: "./src/assets/leisure.png",
    category: "Leisure",
    percentage: "",
    amount: 0,
  },
  {
    id: 3008,
    type: "Expense",
    imageLink: "./src/assets/clothes.png",
    category: "Clothes",
    percentage: "",
    amount: 0,
  },
  {
    id: 3009,
    type: "Expense",
    imageLink: "./src/assets/gifts.png",
    category: "Gifts",
    percentage: "",
    amount: 0,
  },
  {
    id: 3010,
    type: "Expense",
    imageLink: "./src/assets/others.png",
    category: "Other Expenses",
    percentage: "",
    amount: 0,
  },
];

export default MasterData;
